"""
CONTROLLER DEFINES
"""
MAX_SPEED = 100
INITIAL_STEERING_ANGLE = 90*9
MIN_STEERING_ANGLE = 55
MAX_STEERING_ANGLE = 125
STOP_SPEED_RATIO = 0
DEFAULT_SPEED_RATIO = 1
SPEED_RATIO_40 = 1.5
SPEED_RATIO_60 = 2

"""
LANE DETECTOR DEFINES
"""
WHITE_DETECTION_THRESHOLD_LOWER_BOUND = [0, 0, 0]
WHITE_DETECTION_THRESHOLD_UPPER_BOUND = [78, 0, 37]
CAMERA_OFFSET = 0.045
MAX_ANGLE_DEVIATION_FOR_2_LINES = 5
MAX_ANGLE_DEVIATION_FOR_1_LINES = 1.2
LANE_COLOR = (255, 0, 0)
LANE_WIDTH = 10
HEADING_LINE_COLOR = (0, 0, 255)
HEADING_LINE_WIDTH = 5
